include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    directives_ordering: false
    sort_pub_dependencies: false
    implicit_dynamic_type: false