name: wesy
description: Wesy.

publish_to: "none"

version: 1.0.1+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.23.0+1
  equatable: ^2.0.3
  line_icons: ^2.0.1
  gap: ^2.0.0
  go_router: ^2.2.4
  intl: ^0.17.0
  fl_chart: ^0.40.2
  flutter_staggered_animations: ^1.0.0
  auth_repository:
    path: packages/auth_repository
  cs_repository:
    path: packages/cs_repository
  cs_storage:
    path: packages/cs_storage
  cs_ui:
    path: packages/cs_ui
  dartz: ^0.10.0
  data_table_2: ^2.2.0
  table_calendar: ^3.0.3
  horizontal_data_table: ^4.1.2+2
  editable: ^2.0.0
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  bloc: ^8.0.1
  shared_preferences: ^2.0.11
  graphic: ^0.6.2
  calendar_view: ^0.0.3
  google_maps_flutter: ^2.1.1
  flutter_polyline_points: ^1.0.0
  cached_network_image: ^3.2.0
  mime: ^1.0.1
  geolocator: ^8.0.3
  charts_flutter: ^0.12.0
  pie_chart: ^5.1.0
  firebase_core: ^1.12.0
  syncfusion_flutter_calendar: ^19.4.48
  location: ^4.3.0
  firebase_messaging: ^11.2.8
  dropdown_search: ^3.0.1
  image_picker: ^0.8.5+3
  url_launcher: ^6.1.3
  google_geocoding: ^0.2.0
  geocoding: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/wesy_new_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
