name: cs_repository
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  api_client:
    path: ../api_client
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  json_annotation: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  json_serializable: ^6.0.1
  build_runner: ^2.1.4

# The following section is specific to Flutter.
flutter:
