// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQKDo2hsxw2kV-tQijUI8DuM27cGkBtIk',
    appId: '1:456627788531:web:b2fc84297cf02f3d3fb586',
    messagingSenderId: '456627788531',
    projectId: 'company-dashboard-7154b',
    authDomain: 'company-dashboard-7154b.firebaseapp.com',
    storageBucket: 'company-dashboard-7154b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABE0u5aA69QSLhCi6aY75NQZViob2sR2g',
    appId: '1:456627788531:android:847af3a3b8b9f1b03fb586',
    messagingSenderId: '456627788531',
    projectId: 'company-dashboard-7154b',
    storageBucket: 'company-dashboard-7154b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_u3fJA04S-0Fw65C9qerMfJG4-OUSYGc',
    appId: '1:456627788531:ios:2da70976021d3ed93fb586',
    messagingSenderId: '456627788531',
    projectId: 'company-dashboard-7154b',
    storageBucket: 'company-dashboard-7154b.appspot.com',
    iosClientId: '456627788531-93k0db3lpbh7hbafhkbpurosk92al6pa.apps.googleusercontent.com',
    iosBundleId: 'ch.wesy.app',
  );
}
