// Generated by https://quicktype.io

class ImportantNote {
  String? id;
  String? text;
  String? by;
  bool? major;
  String? pin;

  ImportantNote({
    this.id,
    this.text,
    this.by,
    this.major,
    this.pin,
  });

  factory ImportantNote.fromJson(Map<String, dynamic> json) => ImportantNote(
        id: json['_id'] as String,
        text: json['text'] as String,
        by: json['by'] as String,
        major: json['major'] as bool,
        pin: json['pin'] as String,
      );
}
