// Generated by https://quicktype.io

import 'package:cs_repository/cs_repository.dart';

class UploadImage {
  final bool? success;
  final String? message;
  final List<Image>? data;

  UploadImage({
    this.success,
    this.message,
    this.data,
  });

  factory UploadImage.fromJson(Map<String, dynamic> json) => UploadImage(
        success: json['success'] as bool,
        message: json['message'] as String,
        data: json['data'] != null
            ? (json['data'] as List<dynamic>)
                .map((e) => Image.fromJson(e))
                .toList()
            : [],
      );
}
